exec-once = hypridle &
exec-once = hyprlock &
exec-once = waybar & hyprpaper &
exec-once = wl-clipboard-history -t
exec-once = wl-paste --watch cliphist store
exec-once = rm "$HOME/.cache/cliphist/db"

