local km = require("utils.map")
local fs = require("utils.fs")

km.map({ 'n', 'v' }, 'k',  "v:count == 0 ? 'gk' : 'k'", 'Remap k to gk for line sanity', { expr = true })
km.map({ 'n', 'v' }, 'j',  "v:count == 0 ? 'gj' : 'j'", 'Remap j to gj for line sanity', { expr = true })

km.i('kj',          '<ESC>',                             'Press `kj` to invoke Esc')
km.n('<leader>o',   km.cmd("update | source $MYVIMRC"),  'Reload editor')
km.n('<leader>e',   km.cmd("Oil"),                       'Open Oil with `<leader>e`')
km.n('<leader>+',   '<C-a>',                             'Increment number with `<leader>+`')
km.n('<leader>-',   '<C-x>',                             'Decrement number with `<leader>-`')
km.n('<leader>sv',  '<C-w>v',                            'Split window vertically')
km.n('<leader>sh',  '<C-w>s',                            'Split window horizontally')
km.n('<leader>se',  '<C-w>=',                            'Make split windows equal width')
km.n('<leader>sx',  km.cmd("close"),                     'Close current split window')
km.n('<leader>to',  km.cmd("tabnew"),                    'Open new tab')
km.n('<leader>tx',  km.cmd("tabclose"),                  'Close current tab')
km.n('<leader>x',   km.cmd("q"),                         'Close the current buffer')
km.n('<leader>rm',  fs.delete_current_file,              'Delete the current file')
km.n('<C-/>',       'gcc',                               'Toggle comment',          { remap = true })
km.v('<C-/>',       'gc',                                'Toggle comment (visual)', { remap = true })
km.n('<C-h>',       '<C-w>h',                            'Window: Navigate left')
km.n('<C-j>',       '<C-w>j',                            'Window: Navigate down')
km.n('<C-k>',       '<C-w>k',                            'Window: Navigate up')
km.n('<C-l>',       '<C-w>l',                            'Window: Navigate right')

